# Application Name
spring.application.name=curd

# Server Configuration
server.port=8486

# Database Configuration (MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/CRUD
spring.datasource.username=root
spring.datasource.password=root

# Hibernate & JPA Configuration
spring.jpa.properties.hibernate.dialate.=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.root=INFO
logging.level.com.springboottask.springboottask.service=DEBUG
logging.level.com.springboottask.springboottask.controller=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.root-TRACE

# Log File Configuration
logging.file.name=logs/application.log
logging.file.path=logs/
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#logging.logback.rollingpolicy.max-file-size=10MB





	
